default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: key_logger_master
  pool: 5
  username: root
  password: Syhezo9090@
  host: localhost
staging:
  <<: *default
development:
  <<: *default